In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df = pd.read_csv("glucose1.csv")

In [4]:
df

subject  age  glucoselevel
0        1   43            99
1        2   21            69
2        3   25            79
3        4   42            75
4        5   57            87
5        6   59            81

In [5]:
reg = linear_model.LinearRegression()

In [6]:
reg.fit(df.iloc[:,1:2],df.iloc[:,2:3])

LinearRegression()

In [7]:
reg.predict([[55]])

C:\Users\prana\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[86.09630625]])

In [8]:
reg.coef_

array([[0.32021491]])

In [9]:
reg.intercept_

array([68.48448623])